apiVersion: v1
kind: Namespace
metadata:
  name: linebot-namespace

---

apiVersion: v1
kind: ReplicationController
metadata:
   name: linebot
   labels:
      name: linebot
   namespace: linebot-namespace
spec:
   replicas: 1
   selector:
      name: linebot
   template:
      metadata:
         labels:
            name: linebot
      spec:
         containers:
         - name: linebotqna
           image: stanleykao72/linebotqna-multiarch:2
           ports:
           - containerPort: 8000

---

apiVersion: v1
kind: Service 
metadata:
   name: linebot
   labels:
      name: linebot
   namespace: linebot-namespace
spec:
   ports:
   - port: 8000
     targetPort: 8000
   selector:
      name: linebot
