apiVersion: v1
kind: ReplicationController
metadata:
   name: linebot
   labels:
      name: linebot
   namespace: linebot-namespace
spec:
   replicas: 1
   selector:
      name: linebot
   template:
      metadata:
         labels:
            name: linebot
      spec:
         containers:
         - name: linebot
           image: stanleykao72/linebot-multiarch:Django
           ports:
           - containerPort: 8000
           env:
             - name: CHANNEL_ACCESS_TOKEN
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: channel_access_token
             - name: CHANNEL_SECRET
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: channel_secret
             - name: CLIENT_ID
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: client_id
             - name: CLIENT_SECRET
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: client_secret
             - name: ENDPOINT_KEY
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: endpoint_key
             - name: HOST
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: host
             - name: KB
               valueFrom:
                  secretKeyRef:
                     name: system-env
                     key: kb
