apiVersion: batch/v1
kind: Job
metadata:
   name: django-migrations
   namespace: linebot-namespace
spec:
   template:
      spec:
         containers:
         - name: linebot
           image: stanleykao72/linebot-multiarch:Django
           command: ['python', 'manage.py', 'migrate']
         restartPolicy: Never