apiVersion: v1
kind: ReplicationController
metadata:
   name: linebot
   labels:
      name: linebot
spec:
   replicas: 1
   selector:
      name: linebot
   template:
      metadata:
         labels:
            name: linebot
      spec:
         containers:
         - name: linebotqna
           image: stanleykao72/linebotqna-multiarch:2
           ports:
           - containerPort: 8000 
